services:
  gui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    init: true
    ports:
      - "${PUTS_PORT:-3002}:6080"
    volumes:
      - .:/app
      - putslauncher-home:/home/ubuntu

volumes:
  putslauncher-home:
